// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: chatbot

#ifndef _CHATBOT_UI_H
#define _CHATBOT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_ScreenHome.h"
#include "screens/ui_ScreenSettings.h"
#include "screens/ui_ScreenDesktop.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui_Startevents___initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_t2_png);    // assets/t2.png
LV_IMG_DECLARE(ui_img_5_png);    // assets/5.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_7_png);    // assets/7.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font32);
LV_FONT_DECLARE(ui_font_Font40);
LV_FONT_DECLARE(ui_font_Font64);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
