// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: chatbot

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void SettingClick1(lv_event_t * e);
void SettingClick2(lv_event_t * e);
void SettingClick3(lv_event_t * e);
void SettingClick4(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
