// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: chatbot

#include "ui.h"

void SettingClick1(lv_event_t * e)
{
	// Your code here
}

void SettingClick2(lv_event_t * e)
{
	// Your code here
}

void SettingClick3(lv_event_t * e)
{
	// Your code here
}

void SettingClick4(lv_event_t * e)
{
	// Your code here
}

