idf_component_register(SRCS "framework/svc_manager.c" "framework/svc_event.c" "framework/svc_function.c" "svc_wifi.c" "svc_ble.c" "svc_http.c" "svc_audio.c" "svc_display.c" "svc_storage.c" "svc_indicator.c" "svc_time.c" "svc_pm.c" "svc_ota.c" "test_svc.c"
                    INCLUDE_DIRS "."
                    REQUIRES bsp os esp_wifi esp_http_client nvs_flash esp_https_ota app_update bootloader_support lvgl__lvgl esp_lvgl_port esp_driver_i2s esp_driver_ledc bt esp_http_server esp_lcd_touch)