// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: chatbot

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenHome
extern void ui_ScreenHome_screen_init(void);
extern void ui_ScreenHome_screen_destroy(void);
extern void ui_event_ScreenHome(lv_event_t * e);
extern lv_obj_t * ui_ScreenHome;
extern lv_obj_t * ui_HomeLabelData;
extern lv_obj_t * ui_HomeLabelTime;
extern lv_obj_t * ui_HomeLabelweekday;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenHome;
extern lv_obj_t * uic_HomeLabelData;
extern lv_obj_t * uic_HomeLabelTime;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

