// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: chatbot

#include "../ui.h"

lv_obj_t * uic_HomeLabelTime;
lv_obj_t * uic_HomeLabelData;
lv_obj_t * uic_ScreenHome;
lv_obj_t * ui_ScreenHome = NULL;
lv_obj_t * ui_HomeLabelData = NULL;
lv_obj_t * ui_HomeLabelTime = NULL;
lv_obj_t * ui_HomeLabelweekday = NULL;
// event funtions
void ui_event_ScreenHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ScreenDesktop, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenDesktop_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenSettings_screen_init);
    }
}

// build funtions

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_ScreenHome, &ui_img_t2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabelData = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeLabelData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabelData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLabelData, 1);
    lv_obj_set_y(ui_HomeLabelData, -61);
    lv_obj_set_align(ui_HomeLabelData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabelData, "Data");
    lv_obj_set_style_text_color(ui_HomeLabelData, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabelData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLabelData, &ui_font_Font40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabelTime = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeLabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLabelTime, 6);
    lv_obj_set_y(ui_HomeLabelTime, -7);
    lv_obj_set_align(ui_HomeLabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabelTime, "Time");
    lv_obj_set_style_text_color(ui_HomeLabelTime, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLabelTime, &ui_font_Font64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLabelweekday = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeLabelweekday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeLabelweekday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLabelweekday, 8);
    lv_obj_set_y(ui_HomeLabelweekday, 36);
    lv_obj_set_align(ui_HomeLabelweekday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeLabelweekday, "weekday");
    lv_obj_set_style_text_color(ui_HomeLabelweekday, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLabelweekday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLabelweekday, &ui_font_Font32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenHome, ui_event_ScreenHome, LV_EVENT_ALL, NULL);
    uic_ScreenHome = ui_ScreenHome;
    uic_HomeLabelData = ui_HomeLabelData;
    uic_HomeLabelTime = ui_HomeLabelTime;

}

void ui_ScreenHome_screen_destroy(void)
{
    if(ui_ScreenHome) lv_obj_del(ui_ScreenHome);

    // NULL screen variables
    uic_ScreenHome = NULL;
    ui_ScreenHome = NULL;
    uic_HomeLabelData = NULL;
    ui_HomeLabelData = NULL;
    uic_HomeLabelTime = NULL;
    ui_HomeLabelTime = NULL;
    ui_HomeLabelweekday = NULL;

}
