// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: chatbot

#ifndef UI_SCREENDESKTOP_H
#define UI_SCREENDESKTOP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenDesktop
extern void ui_ScreenDesktop_screen_init(void);
extern void ui_ScreenDesktop_screen_destroy(void);
extern void ui_event_ScreenDesktop(lv_event_t * e);
extern lv_obj_t * ui_ScreenDesktop;
extern lv_obj_t * ui_DesktopContainerContainer3;
extern lv_obj_t * ui_DesktopImgbuttonImgButton2;
extern lv_obj_t * ui_DesktopLabelLabel3;
extern lv_obj_t * ui_DesktopContainerContainer2;
extern lv_obj_t * ui_DesktopImgbuttonImgButton3;
extern lv_obj_t * ui_DesktopLabelLabel2;
extern lv_obj_t * ui_DesktopContainerContainer4;
extern lv_obj_t * ui_DesktopImgbuttonImgButton4;
extern lv_obj_t * ui_DesktopLabelLabel4;
extern lv_obj_t * ui_DesktopContainerContainer5;
extern lv_obj_t * ui_DesktopImgbuttonImgButton5;
extern lv_obj_t * ui_DesktopLabelLabel5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenDesktop;
extern lv_obj_t * uic_DesktopLabelLabel3;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

