// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: chatbot

#include "../ui.h"

lv_obj_t * uic_DesktopLabelLabel3;
lv_obj_t * uic_ScreenDesktop;
lv_obj_t * ui_ScreenDesktop = NULL;
lv_obj_t * ui_DesktopContainerContainer3 = NULL;
lv_obj_t * ui_DesktopImgbuttonImgButton2 = NULL;
lv_obj_t * ui_DesktopLabelLabel3 = NULL;
lv_obj_t * ui_DesktopContainerContainer2 = NULL;
lv_obj_t * ui_DesktopImgbuttonImgButton3 = NULL;
lv_obj_t * ui_DesktopLabelLabel2 = NULL;
lv_obj_t * ui_DesktopContainerContainer4 = NULL;
lv_obj_t * ui_DesktopImgbuttonImgButton4 = NULL;
lv_obj_t * ui_DesktopLabelLabel4 = NULL;
lv_obj_t * ui_DesktopContainerContainer5 = NULL;
lv_obj_t * ui_DesktopImgbuttonImgButton5 = NULL;
lv_obj_t * ui_DesktopLabelLabel5 = NULL;
// event funtions
void ui_event_ScreenDesktop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenHome_screen_init);
    }
}

// build funtions

void ui_ScreenDesktop_screen_init(void)
{
    ui_ScreenDesktop = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenDesktop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenDesktop, lv_color_hex(0x0B0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenDesktop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DesktopContainerContainer3 = lv_obj_create(ui_ScreenDesktop);
    lv_obj_remove_style_all(ui_DesktopContainerContainer3);
    lv_obj_set_width(ui_DesktopContainerContainer3, 87);
    lv_obj_set_height(ui_DesktopContainerContainer3, 93);
    lv_obj_set_x(ui_DesktopContainerContainer3, -73);
    lv_obj_set_y(ui_DesktopContainerContainer3, -54);
    lv_obj_set_align(ui_DesktopContainerContainer3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DesktopContainerContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DesktopImgbuttonImgButton2 = lv_imagebutton_create(ui_DesktopContainerContainer3);
    lv_imagebutton_set_src(ui_DesktopImgbuttonImgButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_5_png, NULL);
    lv_obj_set_width(ui_DesktopImgbuttonImgButton2, 64);
    lv_obj_set_height(ui_DesktopImgbuttonImgButton2, 64);
    lv_obj_set_x(ui_DesktopImgbuttonImgButton2, 0);
    lv_obj_set_y(ui_DesktopImgbuttonImgButton2, -8);
    lv_obj_set_align(ui_DesktopImgbuttonImgButton2, LV_ALIGN_CENTER);

    ui_DesktopLabelLabel3 = lv_label_create(ui_DesktopContainerContainer3);
    lv_obj_set_width(ui_DesktopLabelLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DesktopLabelLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DesktopLabelLabel3, 1);
    lv_obj_set_y(ui_DesktopLabelLabel3, 35);
    lv_obj_set_align(ui_DesktopLabelLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DesktopLabelLabel3, "天气");
    lv_obj_set_style_text_color(ui_DesktopLabelLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DesktopLabelLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DesktopLabelLabel3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DesktopContainerContainer2 = lv_obj_create(ui_ScreenDesktop);
    lv_obj_remove_style_all(ui_DesktopContainerContainer2);
    lv_obj_set_width(ui_DesktopContainerContainer2, 87);
    lv_obj_set_height(ui_DesktopContainerContainer2, 93);
    lv_obj_set_x(ui_DesktopContainerContainer2, 63);
    lv_obj_set_y(ui_DesktopContainerContainer2, -54);
    lv_obj_set_align(ui_DesktopContainerContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DesktopContainerContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DesktopImgbuttonImgButton3 = lv_imagebutton_create(ui_DesktopContainerContainer2);
    lv_imagebutton_set_src(ui_DesktopImgbuttonImgButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_2_png, NULL);
    lv_obj_set_width(ui_DesktopImgbuttonImgButton3, 64);
    lv_obj_set_height(ui_DesktopImgbuttonImgButton3, 64);
    lv_obj_set_x(ui_DesktopImgbuttonImgButton3, 0);
    lv_obj_set_y(ui_DesktopImgbuttonImgButton3, -8);
    lv_obj_set_align(ui_DesktopImgbuttonImgButton3, LV_ALIGN_CENTER);

    ui_DesktopLabelLabel2 = lv_label_create(ui_DesktopContainerContainer2);
    lv_obj_set_width(ui_DesktopLabelLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DesktopLabelLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DesktopLabelLabel2, -1);
    lv_obj_set_y(ui_DesktopLabelLabel2, 38);
    lv_obj_set_align(ui_DesktopLabelLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DesktopLabelLabel2, "录音");
    lv_obj_set_style_text_color(ui_DesktopLabelLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DesktopLabelLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DesktopLabelLabel2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DesktopContainerContainer4 = lv_obj_create(ui_ScreenDesktop);
    lv_obj_remove_style_all(ui_DesktopContainerContainer4);
    lv_obj_set_width(ui_DesktopContainerContainer4, 87);
    lv_obj_set_height(ui_DesktopContainerContainer4, 93);
    lv_obj_set_x(ui_DesktopContainerContainer4, -72);
    lv_obj_set_y(ui_DesktopContainerContainer4, 53);
    lv_obj_set_align(ui_DesktopContainerContainer4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DesktopContainerContainer4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DesktopImgbuttonImgButton4 = lv_imagebutton_create(ui_DesktopContainerContainer4);
    lv_imagebutton_set_src(ui_DesktopImgbuttonImgButton4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_7_png, NULL);
    lv_obj_set_width(ui_DesktopImgbuttonImgButton4, 64);
    lv_obj_set_height(ui_DesktopImgbuttonImgButton4, 64);
    lv_obj_set_x(ui_DesktopImgbuttonImgButton4, 0);
    lv_obj_set_y(ui_DesktopImgbuttonImgButton4, -8);
    lv_obj_set_align(ui_DesktopImgbuttonImgButton4, LV_ALIGN_CENTER);

    ui_DesktopLabelLabel4 = lv_label_create(ui_DesktopContainerContainer4);
    lv_obj_set_width(ui_DesktopLabelLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DesktopLabelLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DesktopLabelLabel4, 0);
    lv_obj_set_y(ui_DesktopLabelLabel4, 38);
    lv_obj_set_align(ui_DesktopLabelLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DesktopLabelLabel4, "音乐");
    lv_obj_set_style_text_color(ui_DesktopLabelLabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DesktopLabelLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DesktopLabelLabel4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DesktopContainerContainer5 = lv_obj_create(ui_ScreenDesktop);
    lv_obj_remove_style_all(ui_DesktopContainerContainer5);
    lv_obj_set_width(ui_DesktopContainerContainer5, 87);
    lv_obj_set_height(ui_DesktopContainerContainer5, 93);
    lv_obj_set_x(ui_DesktopContainerContainer5, 63);
    lv_obj_set_y(ui_DesktopContainerContainer5, 52);
    lv_obj_set_align(ui_DesktopContainerContainer5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DesktopContainerContainer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DesktopImgbuttonImgButton5 = lv_imagebutton_create(ui_DesktopContainerContainer5);
    lv_imagebutton_set_src(ui_DesktopImgbuttonImgButton5, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_3_png, NULL);
    lv_obj_set_width(ui_DesktopImgbuttonImgButton5, 64);
    lv_obj_set_height(ui_DesktopImgbuttonImgButton5, 64);
    lv_obj_set_x(ui_DesktopImgbuttonImgButton5, 0);
    lv_obj_set_y(ui_DesktopImgbuttonImgButton5, -8);
    lv_obj_set_align(ui_DesktopImgbuttonImgButton5, LV_ALIGN_CENTER);

    ui_DesktopLabelLabel5 = lv_label_create(ui_DesktopContainerContainer5);
    lv_obj_set_width(ui_DesktopLabelLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DesktopLabelLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DesktopLabelLabel5, -1);
    lv_obj_set_y(ui_DesktopLabelLabel5, 38);
    lv_obj_set_align(ui_DesktopLabelLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DesktopLabelLabel5, "设置");
    lv_obj_set_style_text_color(ui_DesktopLabelLabel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DesktopLabelLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DesktopLabelLabel5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenDesktop, ui_event_ScreenDesktop, LV_EVENT_ALL, NULL);
    uic_ScreenDesktop = ui_ScreenDesktop;
    uic_DesktopLabelLabel3 = ui_DesktopLabelLabel3;

}

void ui_ScreenDesktop_screen_destroy(void)
{
    if(ui_ScreenDesktop) lv_obj_del(ui_ScreenDesktop);

    // NULL screen variables
    uic_ScreenDesktop = NULL;
    ui_ScreenDesktop = NULL;
    ui_DesktopContainerContainer3 = NULL;
    ui_DesktopImgbuttonImgButton2 = NULL;
    uic_DesktopLabelLabel3 = NULL;
    ui_DesktopLabelLabel3 = NULL;
    ui_DesktopContainerContainer2 = NULL;
    ui_DesktopImgbuttonImgButton3 = NULL;
    ui_DesktopLabelLabel2 = NULL;
    ui_DesktopContainerContainer4 = NULL;
    ui_DesktopImgbuttonImgButton4 = NULL;
    ui_DesktopLabelLabel4 = NULL;
    ui_DesktopContainerContainer5 = NULL;
    ui_DesktopImgbuttonImgButton5 = NULL;
    ui_DesktopLabelLabel5 = NULL;

}
